defmodule Day11Test do
  use ExUnit.Case

  test "check day 11" do
    assert Day11.evaluate("""
           ...#......
           .......#..
           #.........
           ..........
           ......#...
           .#........
           .........#
           ..........
           .......#..
           #...#.....
           """) == 374
  end
end
